contents: |
  [Unit]
  Description=Configures SRIOV NIC
  After=network-pre.target
  Before=NetworkManager.service kubelet.service
  
  [Service]
  Type=oneshot
  ExecStart=/var/lib/sriov/sriov-network-config-daemon -v 2 service
  StandardOutput=journal+console
  
  [Install]
  WantedBy=multi-user.target
enabled: true
name: sriov-config.service
