apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  nicSelector: {}
  nodeSelector: {}
  numVfs: 0
  resourceName: ""
